version: "3.1"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
      - ./dump/sampleDB/sample_collection.bson:/db-dump.bson
  bot:
    build:
      context: ./Telbot
      dockerfile: ./dockerfile
    environment:
      - bot="${BOT_TAG}"
    depends_on:
      - mongo